version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notification
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: notification_redis
    ports:
      - "6379:6379"